[settings]
ps_endpoints => pgsql,general,ps_endpoints
ps_aors => pgsql,general,ps_aors
ps_auths => pgsql,general,ps_auths
queues => pgsql,general,asterisk_queues
queue_members => pgsql,general,asterisk_queue_members
voicemail => pgsql,general,asterisk_voicemail
extensions => pgsql,general,asterisk_extensions
musiconhold => pgsql,general,asterisk_moh
