[settings]
ps_endpoints => pgsql,general,ps_endpoints
ps_aors => pgsql,general,ps_aors
ps_auths => pgsql,general,ps_auths
ps_contacts => pgsql,general,ps_contacts
ps_endpoint_id_ips => pgsql,general,ps_endpoint_id_ips
ps_endpoint_id_ips => pgsql,general,ps_endpoint_id_ips
queues => pgsql,general,asterisk_queues
queue_members => pgsql,general,asterisk_queue_members
voicemail => pgsql,general,asterisk_voicemail
extensions => pgsql,general,asterisk_extensions
musiconhold => pgsql,general,asterisk_moh
