[general]
format=wav49|gsm|wav
serveremail=asterisk
attach=yes
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3

[default]
; Voicemail boxes are managed via realtime DB (asterisk_voicemail table)
